export const para= " text-white lg:text-lg text "
export const h1= " text-white lg:text-6xl text-3xl "
export const h2= " text-white lg:text-4xl text-2xl "
export const h3= " text-white lg:text-2xl text-xl "
export const h4= " text-white lg:text-xl text-lg "
export const  primaryButton="  lg:px-4 lg:py-4 px-2 py-2 mx-4 bg-blue-600 border-blue-900 border hover:bg-blue-500 hover:border-blue-700 transition:ease rounded-lg my-4 font-semibold font-sans"
export const  Button="  lg:px-4 lg:py-4 px-2 py-2 mx-4  border-zinc-700 border hover:bg-blue-500 hover:border-blue-700 transition:ease rounded-lg my-4 font-semibold font-sans"
export const WarningButton=" lg:px-4 lg:py-4 px-2 py-2 mx-4 bg-yellow-700  border-yellow-500 border hover:bg-yellow-900 hover:border-yellow-700 transition:ease rounded-lg my-4 font-semibold font-sans "

export const normalInput =" bg-black border border-zinc-700 rounded-lg lg:p-4 p-2 focus:outline-none text-white my-4 mx-4 "